import enum

@enum.unique
class outputs(enum.Enum):
	RESET		= 0
	RIGHT		= 1
	UP_RIGHT	= 2
	UP		= 3
	UP_LEFT		= 4
	LEFT		= 5
	DOWN_LEFT	= 6
	DOWN		= 7
	DOWN_RIGHT	= 8
	TILT_RIGHT	= 9
	TILT_UP		= 10
	TILT_LEFT	= 11
	TILT_DOWN	= 12
	A		= 13
	RIGHT_A		= 14
	UP_A		= 15
	LEFT_A		= 16
	DOWN_A		= 17
	RIGHT_TILT_A	= 18
	UP_TILT_A	= 19
	LEFT_TILT_A	= 20
	DOWN_TILT_A	= 21
	B		= 22
	RIGHT_B		= 23
	UP_B		= 24
	LEFT_B		= 25
	DOWN_B		= 26
	X		= 27
	RIGHT_X		= 28
	LEFT_X		= 29
	R		= 30
	RIGHT_R		= 31
	UP_RIGHT_R	= 32
	UP_R		= 33
	UP_LEFT_R	= 34
	LEFT_R		= 35
	DOWN_LEFT_R	= 36
	DOWN_R		= 37
	DOWN_RIGHT_R	= 38
	Z		= 39

output_map = {outputs.RESET:	"SET MAIN 0.5 0.5\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.RIGHT:		"SET MAIN 1.0 0.5\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.UP_RIGHT:	"SET MAIN 1.0 1.0\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.UP:		"SET MAIN 0.5 1.0\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.UP_LEFT:	"SET MAIN 0.0 1.0\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.LEFT:		"SET MAIN 0.0 0.5\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.DOWN_LEFT:	"SET MAIN 0.0 0.0\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.DOWN:		"SET MAIN 0.5 0.0\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.DOWN_RIGHT:	"SET MAIN 1.0 0.0\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.TILT_RIGHT:	"SET MAIN 0.7 0.5\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.TILT_UP:	"SET MAIN 0.5 0.7\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.TILT_LEFT:	"SET MAIN 0.3 0.5\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.TILT_DOWN:	"SET MAIN 0.5 0.3\nRELEASE A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.A:		"SET MAIN 0.5 0.5\nPRESS A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.RIGHT_A:	"SET MAIN 1.0 0.5\nPRESS A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.UP_A:		"SET MAIN 0.5 1.0\nPRESS A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.LEFT_A:		"SET MAIN 0.0 0.5\nPRESS A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.DOWN_A:		"SET MAIN 0.5 0.0\nPRESS A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.RIGHT_TILT_A:	"SET MAIN 0.7 0.5\nPRESS A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.UP_TILT_A:	"SET MAIN 0.5 0.7\nPRESS A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.LEFT_TILT_A:	"SET MAIN 0.3 0.5\nPRESS A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.DOWN_TILT_A:	"SET MAIN 0.5 0.3\nPRESS A\nRELEASE B\nRELEASE X\nRELEASE R\n",
	outputs.B:		"SET MAIN 0.5 0.5\nPRESS B\nRELEASE A\nRELEASE X\nRELEASE R\n",
	outputs.RIGHT_B:	"SET MAIN 1.0 0.5\nPRESS B\nRELEASE A\nRELEASE X\nRELEASE R\n",
	outputs.UP_B:		"SET MAIN 0.5 1.0\nPRESS B\nRELEASE A\nRELEASE X\nRELEASE R\n",
	outputs.LEFT_B:		"SET MAIN 0.0 0.5\nPRESS B\nRELEASE A\nRELEASE X\nRELEASE R\n",
	outputs.DOWN_B:		"SET MAIN 0.5 0.0\nPRESS B\nRELEASE A\nRELEASE X\nRELEASE R\n",
	outputs.X:		"SET MAIN 0.5 0.5\nPRESS X\nRELEASE A\nRELEASE B\nRELEASE R\n",
	outputs.RIGHT_X:	"SET MAIN 1.0 0.5\nPRESS X\nRELEASE A\nRELEASE B\nRELEASE R\n",
	outputs.LEFT_X:		"SET MAIN 0.0 0.5\nPRESS X\nRELEASE A\nRELEASE B\nRELEASE R\n",
	outputs.R:		"SET MAIN 0.5 0.5\nPRESS R\nRELEASE A\nRELEASE B\nRELEASE X\n",
	outputs.RIGHT_R:	"SET MAIN 1.0 0.5\nPRESS R\nRELEASE A\nRELEASE B\nRELEASE X\n",
	outputs.UP_RIGHT_R:	"SET MAIN 1.0 1.0\nPRESS R\nRELEASE A\nRELEASE B\nRELEASE X\n",
	outputs.UP_R:		"SET MAIN 0.5 1.0\nPRESS R\nRELEASE A\nRELEASE B\nRELEASE X\n",
	outputs.UP_LEFT_R:	"SET MAIN 0.0 1.0\nPRESS R\nRELEASE A\nRELEASE B\nRELEASE X\n",
	outputs.LEFT_R:		"SET MAIN 0.0 0.5\nPRESS R\nRELEASE A\nRELEASE B\nRELEASE X\n",
	outputs.DOWN_LEFT_R:	"SET MAIN 0.0 0.0\nPRESS R\nRELEASE A\nRELEASE B\nRELEASE X\n",
	outputs.DOWN_R:		"SET MAIN 0.5 0.0\nPRESS R\nRELEASE A\nRELEASE B\nRELEASE X\n",
	outputs.DOWN_RIGHT_R:	"SET MAIN 1.0 0.0\nPRESS R\nRELEASE A\nRELEASE B\nRELEASE X\n",
	outputs.Z:		"SET MAIN 0.5 0.5\nPRESS A\nPRESS R\nRELEASE B\nRELEASE X\n"}
